version: '3.8'

services:
  app:
    build: 
      content: ./backend
    ports:
      -'8080:8080'
    environment:
      - MONGODB_URI: ${MONGODB_URI}

  frontend:
    build: 
      content: ./frontend
    ports:
      -'5173:80'

    